src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rule_set__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable Workflow Rule</description>
        <inlineHelpText>Enable Workflow Rule</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <inlineHelpText>Object Name</inlineHelpText>
        <label>Object Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Rule set</label>
    <nameField>
        <label>Rule set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advanced_Filter__c</fullName>
        <description>Filter logic lets you apply Boolean conditions to filters to hone in on the data you’re looking for.</description>
        <inlineHelpText>You can enter filter line numbers in any order. i.e. (1 AND 2) OR 3</inlineHelpText>
        <label>Advanced Filter</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayActions__c</fullName>
        <description>This is field is update via trigger AW_trg_RuleAction everytime an action is updated or inserted The purpose of the field is to show ALL actions of a rule in a summary level as follows :
Collect all actions assigned to the rule 
Each rule action will be displayed in separate line in URL format  
For each action show the first 100 chars by concatenating the fields  Type__c&amp;&amp; Related_Object__c &amp;&amp; DispalyField__c with a &quot;...&quot;  in URL Format 
The URL would take the user to this Rule Action Display Page for the Rule Action ID
If you hover on that you get show the full value of RuleAction__c.DisplayfilterLogic__c present</description>
        <label>Display Actions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayfilterLogic__c</fullName>
        <description>Captures  logic expression  using the fileds of the defined rule criteria as operands ( rule criteria ) For Example : if a rule had 3 criteria : Criteria 1 ( Industry  =   &apos;Banking&apos; ) , Criteria 2 (Country=&apos;United States&apos;) , Criteria 3 (Type=&apos;Active&apos;  ) the Display Filter logic for  : Criteria  1 AND Criteria  2 OR Criteria  3   would be   Industry  =   &apos;Banking&apos; AND Country=&apos;United States&apos; OR Type=&apos;Active&apos;
During save the DisplayfilterLogic is calculated based on the value captured on  the Filter_Logic value ( 1 AND 2 OR 3 ) The calcuation derives the field name of the rule criteria  for the positional operators. The field is used for display purposes  to the user</description>
        <label>Rule Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation_Rule__c</fullName>
        <label>Evaluation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created or edited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Click Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <description>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</description>
        <inlineHelpText>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</inlineHelpText>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormattedFilterLogic__c</fullName>
        <description>Captures  logic expression  using the Salesforce Unique IDs of the defined rule criteria as operands ( rule criteria ) For Example : if a rule had 3 criteria : Criteria 1 (a0NA000000Rt5nTMAR ) , Criteria 2 (a0NA000000Rt5nYMAR ) , Criteria 3 (a0NA000000Rt5nYMAR  ) the Formatted Filter logic for  : Criteria  1 AND Criteria  2 OR Criteria  3   would be  a0NA000000Rt5nTMAR AND a0NA000000Rt5nYMAR OR a0NA000000Rt5nnMAB
During save the FormatedFilterLogic is calculated based on the value captured on  the Filter_Logic value ( 1 AND 2 OR 3 ) The calcuation derives the SFDC id for the positional operators. The field is used hidden to the user and serves to &quot;map&quot; the logic expression with the criteria records</description>
        <label>FormattedFilterLogic</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ruleset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule set</label>
        <referenceTo>Rule_set__c</referenceTo>
        <relationshipLabel>Workflow Rules</relationshipLabel>
        <relationshipName>Workflow_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Workflow Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRuleAction__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Update Field</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Related Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoke Apex</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action_Object__c</fullName>
        <label>Action Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Additional_Emails__c</fullName>
        <label>Additional Emails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Value__c</fullName>
        <label>Long Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Owner_Id__c</fullName>
        <label>User/Owner Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkflowRuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Object__c</fullName>
        <label>Criteria Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Equal To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ends With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excludes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Field__c</fullName>
        <label>Parent Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <label>Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkflowRuleEvaluation.cls
public with sharing class WorkflowRuleEvaluation {
        
    
    //required to stop the trigger to start
    public static Boolean EvaluationIsRunning=false;
    
    
    //required for trigger chaining every trigger that calls this class will add it self to this set so
    //that the same sobject trigger does not start evaluation running
    public static Set<String> EvaluationRunningFor = new Set<String>();
    
    //stores the fields that needs to be quired
    public static Map<String,Set<String>> criteriaFields;  
     
    // Child object to be inserted
    public static List<SObject> childObjectList = new List<SObject>();
    
    // Map of Rule Action Id and Insert Related Record Info object as child 
    public static Map<Id,WorkflowRuleAction__c> insertedRelatedRecordInfo = new Map<Id,WorkflowRuleAction__c>();
    
    // Map of child relationship name and field in child for parent
    public static Map<String,String> childParentRelationshipField = new Map<string,String>();
    
    
    public static Map<Id,SObject> toUpdateSObject;      
    
    public static Boolean failTrigger = false;
        
    /** added this variable to hold the oldRecords in case of update **/
    public static  Map<Id,SObject> oldListMap = new Map<Id,SObject>();
    public static Boolean isUpdate=false;
         
         
   /**
    * this method starts the processing engine for evaluation the rules
    * params : 
    * recordIds : ids of the object records that needs to be evaluated 
    * sobjectName : object(Account,Contact)
    * action : update/insert      
    */
    public static void startWorkflow(Set<Id> recordIds,String sobjectName,Boolean isInsert){        
        System.debug('----> Start Workflow: Enter');
        system.debug('==>'+recordIds);
        // get the rules get all types of rules
        String query = 'Select SystemModstamp, OwnerId, Object_Name__c, Name, LastModifiedDate, LastModifiedById, LastActivityDate, IsDeleted, Id, CreatedDate, CreatedById, Active__c, (Select Id, OwnerId, IsDeleted, Name, RecordTypeId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, Active__c, Description__c, DisplayActions__c, DisplayfilterLogic__c, Evaluation_Rule__c, Filter_Logic__c, FormattedFilterLogic__c, Object_Name__c, Order__c, Status__c, Version__c, Effective_Date__c, Expiration_Date__c, Advanced_Filter__c, Ruleset__c From Workflow_Rules__r WHERE Active__c=true ';
        //String query ='Select Id,Evaluation_Rule__c,Object_Name__c FROM WorkflowRule__c WHERE Object_Name__c=\''+sobjectName+'\' AND Active__c=true';
        isUpdate = !isInsert;
        
        if(!isInsert){
            query+=' AND Evaluation_Rule__c!=\'Record is created\'';
        }
        query +=') From Rule_set__c WHERE Object_Name__c=\''+sobjectName+'\' AND Active__c=true';
        //list of rule set
        list<Rule_set__c> rulesetList = database.query(query);
        //list of rules
        List<WorkflowRule__c> ruleList = new list<WorkflowRule__c>();
        for(Rule_set__c rulesetrecord: rulesetList){
        	ruleList.addall(rulesetrecord.Workflow_Rules__r);
        }
        if(ruleList.size()==0) 
        return;
        
        Map<Id,WorkflowRule__c> rules = new Map<Id,WorkflowRule__c> (ruleList);
        evaluateWorkflowRules(rules.keySet(),recordIds,sobjectName);
        System.debug('----> Start Workflow: Exit');
    }
    
    
    /*
      this is where the entire execution process is started:-
      Get all the rules defined for this sobject
      & evalaute those rule against the records
    */
            
    public static Boolean evaluateWorkflowRules(Set<Id> ruleIds,Set<Id> recordIds,String sobjectName){ 
            System.debug('----> Evaluate Workflow Rules: Enter');
            system.debug('==>'+recordIds);
            /*
              get the criteria,actions for the rules
            */
            List<WorkflowRule__c> rules = WorkflowRuleHelper.getWorkflowRuleDetails(ruleIds);
            
            /*
              Once we get the workflowRuleCriteria build the criteria fields to query
              so that we can only fetch the required fields
            */
            initFieldInvolvedInCriteria(rules,sobjectName); 
            //system.debug(criteriaFields);
            /*
              Once we get the workflowRuleActions build the action fields to query
              so that we can only fetch the required fields
            */
            WorkflowActionHelper.initFieldInvolvedInActions(rules,sobjectName);
            //system.debug(criteriaFields);
            
            //initialize the mapping records
            insertedRelatedRecordInfo = WorkflowRuleHelper.getInsertRelatedRecordInfo(ruleIds);
            
            //Set this flag on needed for recursive trigger calls
            EvaluationIsRunning=true;
            
            //now done let use fetch the records for executiong & evaluation
            Set<String> parentFields = criteriaFields.get(sobjectName.toLowerCase())==null?
                                       new Set<String>():criteriaFields.get(sobjectName.toLowerCase());
                                        
            
            List<String> lstFields = new List<String>();
            
            if(parentFields==null || parentFields.size()==0 || !parentFields.contains('id')) {
                parentFields.add('id');         
            }
            
            lstFields.addAll(parentFields);
            String fields = String.join(lstFields,',');

           
            String qrySOQL='';
           
            qrySOQL='SELECT  ' + fields +' ';
            
             //now add the child queries also as they need to be evaluated in the query :)
            for(String obj:criteriaFields.keySet()){
                if(obj.equalsIgnoreCase(sobjectName.toLowerCase())) continue;                 
                lstFields = new List<String>();    
                lstFields.addAll(criteriaFields.get(obj));     
                fields =String.join(lstFields,',');
                if(fields!= null && fields != ''){
                    qrySOQL+=' , (SELECT  ' + fields +',Id  FROM '+obj+')';
                }
            }
              
            qrySOQL+=' FROM '+sobjectName+' WHERE Id IN : recordIds';
            system.debug('=====qrySOQL====>'+qrySOQL);
            system.debug('=====qrySOQL====>'+recordIds);
            List<SObject> sobjectRecords = database.query(qrySOQL);  
            
            toUpdateSObject= new Map<Id,SObject>();
            childObjectList = new List<SObject>(); 
            
            Map<String,List<SObject>> toUpdateChildObjects = new Map<String,List<SObject>>();
             
            Map<String,Map<String,List<WorkflowRuleAction__c>>> usersInSendEmailAction =new Map<String,Map<String,List<WorkflowRuleAction__c>>> ();
            Map<String,Map<String,List<WorkflowRuleAction__c>>> grpsInSendEmailAction = new Map<String,Map<String,List<WorkflowRuleAction__c>>> ();
            
            
           //start the evaluation for each rule
            for(SObject so:sobjectRecords){
                
                for(WorkflowRule__c rule : rules){
                    System.debug('----------------------------WorkflowRule Start => '+ rule.Id +'/'+ rule.Name +'----------------------------');
                    Boolean isValid = evaluateRule(so,rule);
                    if(isValid){                    
                            //the rule has met all the conditions time for action :)
                            for(WorkflowRuleAction__c action : rule.Workflow_Rule_Actions__r){
                                    System.debug('----> WorkflowRuleAction__c => ActionType__c: ' + action.ActionType__c);
                                
                                    if(action.ActionType__c == 'Send Email'){
                                         Id sendTo = action.User_Owner_Id__c !=null ? Id.valueof(action.User_Owner_Id__c):UserInfo.getUserId();
                                         if(action.additional_emails__c!=null){
                                            action.additional_emails__c = WorkflowMergeFormulaHelper.doMerge(action.additional_emails__c.replaceAll(',','&'),so);
                                            action.additional_emails__c = action.additional_emails__c.replaceAll(' ',',');
                                         }
                                         
                                         if(sendTo.getSObjectType() == User.SobjectType ){                                                                           
                                            usersInSendEmailAction=WorkflowActionHelper.buildListForEmail(usersInSendEmailAction,sendTo,action,so.Id);
                                         }else if(sendTo.getSObjectType() == Group.SobjectType){                                            
                                            grpsInSendEmailAction=WorkflowActionHelper.buildListForEmail(grpsInSendEmailAction,sendTo,action,so.Id);
                                         } 
                                    }else if(action.ActionType__c=='Update Field'){
                                            applyUpdateAction(action,so);
                                    }
                                    else if(action.ActionType__c=='Insert Related Object'){
                                        String parentFieldName = childParentRelationshipField.get(action.Action_Object__c.tolowerCase());
                                         /**
                                        * Dynamically create child instance
                                        */
                                        Type t = Type.forName(action.Action_Object__c);
                                        SOBject newObj = (SObject)t.newInstance();  
                                        
                                         if(action.Action_Object__c.tolowerCase()=='task'){
                                            if(so.Id.getSObjectType() == User.SobjectType){
                                                parentFieldName='OwnerId';
                                            }else  if(so.Id.getSObjectType() == Contact.SobjectType || so.Id.getSObjectType() == Lead.SobjectType){
                                                parentFieldName='WhoId';
                                            }
                                            if(so.Id.getSObjectType() != Contact.SobjectType && so.Id.getSObjectType() != Lead.SobjectType){
                                                parentFieldName='WhatId';
                                            }
                                        }
                                      
                                         if (parentFieldName!= null ) newObj = WorkflowActionHelper.updateField(action,parentFieldName,so.Id,newObj);
                                         /**
                                          * Apply rest of the fields
                                          */
                                        
                                         newObj = WorkflowActionHelper.applyInsertChildActions(action,newObj,so);
                                        
                                         childObjectList.add(newObj);   
                                         system.debug('----> newObj: ' + newObj);
                                    }else if(action.actiontype__c=='Notification'){
                                        
                                        WorkflowNotification__c  notify= new WorkflowNotification__c(message__c=action.long_value__c);
                                        childObjectList.add(notify);  
                                        
                                    }else if(action.actiontype__c=='Error'){
                                        //error time
                                        throw new WorkflowException(action.long_value__c);
                                    }
                                
                                
                            }//end rule action
                        
                    }//end isvalid
                    System.debug('----------------------------WorkflowRule Exit => '+ rule.Id +'----------------------------');
                }//end workflow rule
            }//end sobject records
            
            
            if(toUpdateSObject.size()>0) update toUpdateSObject.values();
        
            try {
              if(childObjectList.size()>0) insert childObjectList;
            } catch (DmlException e) {
              System.debug('-----> Error has occured in workflow for Inserting child objects. Message: ' + e.getMessage());
            }
            
            if(WorkflowActionHelper.userIdMailContentMap!=null && WorkflowActionHelper.userIdMailContentMap.size()>0){
                         Map<Id,User> userDetails = WorkflowRuleHelper.getUserDetails(WorkflowActionHelper.userIdMailContentMap.keySet());
                         new WorkflowSendEmailUtil ().sendEmail(userDetails ,WorkflowActionHelper.userIdMailContentMap);
            }
           /*      
           if(grpsInSendEmailAction!=null & grpsInSendEmailAction.size()>0){
                //get the list of users in that group:-
                List<Group> grps =[Select Id,(Select UserOrGroupId FROM GroupMembers) FROM Group WHERE Id IN:grpsInSendEmailAction.keySet()];
                
                for(Group g:grps){
                     for(GroupMember gm:g.GroupMembers){
                            for( String objId : grpsInSendEmailAction.get(g.Id).keySet()){
                                    
                                   for(WorkflowRuleAction__c template :  grpsInSendEmailAction.get(g.Id).get(objId)){
                                        usersInSendEmailAction= WorkflowActionHelper.buildListForEmail(usersInSendEmailAction, gm.UserOrGroupId, template,objId);
                                   }  
                                    
                            }
                     }
                }
                
           }
           */
           //finally sending emails :-
           if(usersInSendEmailAction!=null &&   usersInSendEmailAction.size()>0){
                  Map<Id,User> userDetails = WorkflowRuleHelper.getUserDetails(usersInSendEmailAction.keySet());
                  new WorkflowSendEmailUtil ().sendEmail(userDetails ,usersInSendEmailAction);
           } 
            
        System.debug('----> Evaluate Workflow Rules: Exit');
        return true; 
    }
    
        /*
        @purpose:
            method evaluates the rule to true/false for the sobject record
        */
        private static Boolean evaluateRule(SObject so,WorkflowRule__c rule){ 
            Boolean evaluateRule = true;
            if(isUpdate  && rule.Evaluation_Rule__c.equals('Record is created or edited and did not previously meet the rule criteria')){
                evaluateRule =false;
                if(oldListMap != null && oldListMap .size()>0 && oldListMap.get(so.Id)!=null){
                   SOBject obj= oldListMap.get(so.Id);
                   for(WorkflowRuleCriteria__c criteria :rule.Workflow_Rule_Criterias__r){ 
                        /* For cross formula fields the evaluation created or edited and did not previously meet does not work 
                           cross formula fields are located in other objects and we do not have a way to trap the change*/
                        if(criteria.Child_Relationship_Name__c!=null || criteria.Parent_Object_Field__c!=null){
                            evaluateRule =false;
                            continue;
                        }
                        if(so.get(criteria.Field_API_Name__c) != obj.get(criteria.Field_API_Name__c)){
                            evaluateRule = true;
                            break;
                        }
                   } 
                }           
            }
            if(!evaluateRule ) return false; 
            
            //CRITERIA LOGIC
            Set<Boolean> results= new Set<Boolean>();
            String filterLogic = rule.Filter_Logic__c;
            
            for(WorkflowRuleCriteria__c criteria :rule.Workflow_Rule_Criterias__r){ 
                    System.debug('----> Criteria: ' + criteria);
                    //evaluate each criteria to decide
                    if(criteria.Child_Relationship_Name__c!=null){
                        //evaluate child records
                        Boolean childResult=true;
                        for(SObject cso : so.getSObjects(criteria.Child_Relationship_Name__c)){
                            if(checkCriteria(String.valueof(cso.get(criteria.Field_API_Name__c)),criteria)){
                                childResult=false;
                                break;
                            }
                        }
                        results.add(childResult);
                    }else if(String.isBlank(criteria.Parent_Object_Field__c)){
                        results.add(checkCriteria(String.valueof(so.get(criteria.Field_API_Name__c)),criteria));
                        System.debug('----> IS BLANK result: ' + checkCriteria(String.valueof(so.get(criteria.Field_API_Name__c)),criteria));
                    }else if(!String.isBlank(criteria.Parent_Object_Field__c)){
                        SObject pso = so.getSObject(criteria.relationship_name__c);
                        results.add(pso!=null ? checkCriteria(String.valueof(pso.get(criteria.Parent_Object_Field__c)),criteria):false);
                    }
            }
            return  (rule.Filter_Logic__c == 'AND' ? !results.contains(false) : results.contains(true));
        }

        private static Boolean checkCriteria(String fieldValue,WorkflowRuleCriteria__c criteria){
                
            Boolean result=false;
            
            //support null / is null operator
            if(criteria.Operator__c.equalsIgnoreCase('Is Null') || criteria.Operator__c.equalsIgnoreCase('Is Not Null')){
                     result =  WorkflowComparisonHelper.isValid(fieldValue,criteria.Value__c,criteria.Operator__c); 
                     return result;
            }
                        
            if (!String.isBlank(fieldValue)){ 
                
                String comparisonValue = criteria.Value__c;
                
                String fieldtype = criteria.Field_Type__c;
                // Check the field type
                if (fieldType == 'integer' || fieldType == 'double'){
                    result = WorkflowComparisonHelper.isValid(decimal.valueOf(fieldValue),decimal.valueOf(comparisonValue),criteria.Operator__c,criteria);                 
                }else if (fieldType == 'date'){
                    result = WorkflowComparisonHelper.isValid(WorkflowRuleUtils.convertStringToDate(fieldValue), WorkflowRuleUtils.convertStringToDate(comparisonValue),criteria.Operator__c,criteria);                     
                }else if (fieldType == 'datetime'){
                    result = WorkflowComparisonHelper.isValid(WorkflowRuleUtils.convertStringToDateTime(fieldValue), WorkflowRuleUtils.convertStringToDateTime(comparisonValue),criteria.Operator__c,criteria);                 
                }else{
                    result = WorkflowComparisonHelper.isValid(fieldValue,comparisonValue,criteria.Operator__c);                 
                }                             
            }
            return result;
                
        }
        


    
    
    /**
    * this method   gets all the fields involved in the criteria for evaluation
    */
    private  static void initFieldInvolvedInCriteria(List<WorkflowRule__c> rules ,String sobjectName){
    
        criteriaFields = new Map<String,Set<String>>();                               
        for(workflowRule__c rule:rules){
            for(WorkflowRuleCriteria__c criteria :rule.Workflow_Rule_Criterias__r){             
                system.debug('WorkflowRuleCriteria__c-->'+criteria);
               //for the main object if the relation ship is not defined take the rule object
               String key = criteria.Child_Relationship_Name__c!=null ? criteria.Child_Relationship_Name__c.toLowerCase() : criteria.Criteria_Object__c.toLowerCase(); 
                 
               String field =  criteria.Parent_Object_Field__c!=null?  criteria.Relationship_Name__c+'.'+criteria.Parent_Object_Field__c : criteria.Field_API_Name__c;
                   
               Set<String> fieldToAdd = criteriaFields.get(key)!=null ? criteriaFields.get(key): new Set<String>();            
               if(!fieldToAdd.contains(field.toLowerCase()))fieldToAdd.add(field.toLowerCase());
               criteriaFields.put(key,fieldToAdd);
             }           
        }
       
    }
    
    private static void applyUpdateAction(WorkflowRuleAction__c action,SObject o){
        SObject o1 =  action.Field_Name__c=='CrossObject' &&  !action.CrossObjectField__c.startsWithIgnoreCase('{!What') ? o.getSObject(action.CrossObjectField__c.substringbetween('{!','}').split('\\.')[0]): o;
        
        if(o1!=null && action.ActionType__c == 'Update Field'){
            
            o1= toUpdateSObject.get(String.valueof(o1.get('id'))) ==null?
                o1 : toUpdateSObject.get(String.valueof(o1.get('id')));
            
            String value = WorkflowActionHelper.getValueForUpdateAction(action);
            String fieldToUpdate = action.Field_Name__c=='CrossObject' ? action.CrossObjectField__c.substringbetween('{!','}').split('\\.')[1] :action.Field_Name__c;
                         
           
            if(action.child_relationship_name__c!=null){
                //update child objects
                //itz a action on the child object:-               
                for(SObject co :o.getSObjects(action.child_relationship_name__c)){
                     if(value!=null){
                        value =   WorkflowMergeFormulaHelper.resolveValueFetched (action,value,co); 
                        co = WorkflowActionHelper.updateField(action,action.field_name__c,action.value__c,co);
                        toUpdateSObject.put(String.valueof(co.get('id')),co);
                     }
                }                
                return;
            }
            else if(action.Field_Name__c=='CrossObject' && action.CrossObjectField__c.substringbetween('{!','}').startsWithIgnoreCase('What')){
                //get the what id from task & update the parent:-
                SObject taskObj = Database.query('Select WhatId FROM Task WHERE Id =\''+String.valueof(o1.get('id'))+'\'');     
                //once task object if fetched
                String whatid= String.valueOf(taskObj.get('WhatId'));
                //finnaly get the parent object & field update will then be spl
                o1 = toUpdateSObject.get(whatid);
                if(o1==null){
                    //now get the sobject:-
                    o1 =Database.query('Select '+fieldToUpdate+' FROM '+String.valueof(Id.valueOf(whatid).getSObjectType())+' WHERE Id=\''+whatid+'\'');
                }                           
            }
           /*else {
                o1 = WorkflowActionHelper.updateField(action,fieldToUpdate,value,o1);
                toUpdateSObject.put(String.valueof(o1.get('id')),o1);   
           }
           */
           
            if(value!=null){                     
                value =   WorkflowMergeFormulaHelper.resolveValueFetched (action,value,o); 
                o1 = WorkflowActionHelper.updateField(action,fieldToUpdate,value,o1);
                toUpdateSObject.put(String.valueof(o1.get('id')),o1);         
            }
                 
        }
                           
    }
    
   
}