src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkflowRule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <description>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</description>
        <inlineHelpText>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</inlineHelpText>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Workflow Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Criteria_Object__c</fullName>
        <label>Criteria Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Equal To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ends With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excludes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Field__c</fullName>
        <label>Parent Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Name__c</fullName>
        <label>Parent Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkflowRuleCriteriaControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class WorkflowRuleCriteriaControllerTest {
    
    
    /*
    * Method used to test the constructor
    */ 
    static testMethod void test_Constructor(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));
        ApexPages.StandardController ctrl = new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND'));
        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(ctrl);
        System.assertEquals(0,cls.workflowCriteriaList.size());
        Test.stopTest();
    }


    /*
    * Method used to test the OrgObjects
    */ 
    static testMethod void test_OrgObjects(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));
        ApexPages.StandardController ctrl = new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND'));
        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(ctrl);
        System.assertNotEquals(0,cls.getOrgObjects().size());
        Test.stopTest();
    }

    /*
    * Method used to test the show criteria method
    */ 
    static testMethod void test_showCriteria(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));
        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND')));
        cls.showCriteria();
        System.assertEquals(1,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        Test.stopTest();
    }


    /*
    * Method used to test the ad criteria method
    */ 
    static testMethod void test_addCriteria(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));
        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND')));
        cls.showCriteria();
        System.assertEquals(1,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());

        cls.addCriteria();
        System.assertEquals(2,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        cls.addCriteria();

        System.assertEquals(3,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        Test.stopTest();
    }

    /*
    * Method used to test the delete criteria method
    */ 
    static testMethod void test_deleteCriteria(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));
        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND')));
        cls.showCriteria();
        System.assertEquals(1,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        
        cls.addCriteria();
        System.assertEquals(2,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        
        cls.addCriteria();
        System.assertEquals(3,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());

        cls.counter = 1;
        cls.deleteCriteria();
        System.assertEquals(2,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());

        cls.counter = 1;
        cls.deleteCriteria();
        System.assertEquals(1,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        Test.stopTest();
    }
    
    
    /*
    * Method used to test the saveworkflowRule method
    */ 
    static testMethod void test_saveworkflowRule(){
        Test.startTest();
        System.Test.setCurrentPage(new PageReference('/apex/x'));

        WorkflowRuleCriteriaController cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(new WorkflowRule__c()));
        // Save the scoring rule and check the errors
        // Negative cases 
        System.assertEquals(null,cls.saveworkflowRule());
       

        // Positive  cases 
        cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(new WorkflowRule__c(Name='Test scoring rule',Object_Name__c='account',Active__c=true,Filter_Logic__c='AND')));
        cls.showCriteria();
        System.assertEquals(1,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());
        
        cls.addCriteria();
        System.assertEquals(2,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());

        cls.addCriteria();
        System.assertEquals(3,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());

        cls.addCriteria();
        System.assertEquals(4,cls.workflowCriteriaList.size());
        System.assertNotEquals(0,cls.workflowCriteriaList.size());


        // Set the field name and values 
        cls.workflowCriteriaList[0].workflowRuleCriteria.criteria_object__c = 'account';
        cls.workflowCriteriaList[0].isReference();        
        cls.workflowCriteriaList[0].workflowRuleCriteria.Field_Name__c = 'rating';
        cls.workflowCriteriaList[0].workflowRuleCriteria.Field_API_Name__c = 'rating';
        cls.workflowCriteriaList[0].isReference();
        cls.workflowCriteriaList[0].workflowRuleCriteria.Operator__c = 'equals';
        cls.workflowCriteriaList[0].dataObject.put('rating','High');

        // Set the second
        cls.workflowCriteriaList[1].workflowRuleCriteria.criteria_object__c = 'case';
        cls.workflowCriteriaList[1].workflowRuleCriteria.Field_Name__c = 'status';
        cls.workflowCriteriaList[1].workflowRuleCriteria.Field_API_Name__c = 'status';
        cls.workflowCriteriaList[1].isReference();
        cls.workflowCriteriaList[1].workflowRuleCriteria.Operator__c = 'equals';
        cls.workflowCriteriaList[1].dataObject.put('status','Open');

        // Set the third
        cls.workflowCriteriaList[2].workflowRuleCriteria.criteria_object__c = 'account';
        cls.workflowCriteriaList[2].workflowRuleCriteria.Field_Name__c = 'numberofemployees';
        cls.workflowCriteriaList[2].workflowRuleCriteria.Field_API_Name__c = 'numberofemployees';
        cls.workflowCriteriaList[2].isReference();
        cls.workflowCriteriaList[2].workflowRuleCriteria.Operator__c = 'equals';
        cls.workflowCriteriaList[2].dataObject.put('numberofemployees',2000);

        // Set the fourth
        cls.workflowCriteriaList[3].workflowRuleCriteria.criteria_object__c = 'account';
        cls.workflowCriteriaList[3].workflowRuleCriteria.Field_Name__c = 'parentid';
        cls.workflowCriteriaList[3].workflowRuleCriteria.Field_API_Name__c = 'parentid';
        cls.workflowCriteriaList[3].isReference();
        cls.workflowCriteriaList[3].workflowRuleCriteria.Parent_Object_Name__c = 'account';
        cls.workflowCriteriaList[3].workflowRuleCriteria.Parent_Object_Field__c = 'rating';
        cls.workflowCriteriaList[3].setParentField();
        cls.workflowCriteriaList[3].workflowRuleCriteria.Operator__c = 'equals';
        cls.workflowCriteriaList[3].dataObject.put('rating','High');

        System.assertNotEquals(null,cls.saveworkflowRule());

        // Check the scoring rule and its criteria 
        WorkflowRule__c workflowRule = [SELECT Id, Object_Name__c, Active__c,  
                                            (SELECT Id, Field_Name__c, Field_Type__c, Operator__c, Parent_Object_Field__c, 
                                                    Parent_Object_Name__c, Value__c
                                                        FROM Workflow_Rule_Criterias__r) 
                                            FROM WorkflowRule__c LIMIT 1];

        // Check the values 
        System.assertEquals('account',workflowRule.Object_Name__c);
        System.assert(workflowRule.Active__c);
        System.assertEquals(4,workflowRule.Workflow_Rule_Criterias__r.size());

        // Call the constructor again and check the values 
        cls = new WorkflowRuleCriteriaController(new ApexPages.standardController(workflowRule));
        System.assertEquals(4,cls.workflowCriteriaList.size());

    }
}