src/objects/WorkflowRule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluation_Rule__c</fullName>
        <label>Evaluation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created or edited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Click Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <description>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</description>
        <inlineHelpText>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</inlineHelpText>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Workflow Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkflowRuleAction__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ActionType__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Update Field</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Related Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoke Apex</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action_Label__c</fullName>
        <description>name for the action</description>
        <label>Action Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Object__c</fullName>
        <label>Action Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Additional_Emails__c</fullName>
        <label>Additional Emails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CrossObjectField__c</fullName>
        <inlineHelpText>Cross Object Field Notation :  Relationshipname.FieldName. Eg:- Account.Type</inlineHelpText>
        <label>Cross Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <label>Email Template</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Field_API_Name__c</fullName>
        <defaultValue>&quot;Id&quot;</defaultValue>
        <description>store the external field on which upsert will happen</description>
        <label>External Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Value__c</fullName>
        <label>Long Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notified_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notified User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workflow_Rule_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notify_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <label>Reference Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Owner_Id__c</fullName>
        <label>User/Owner Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkflowRuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Child_Relationship_Name__c</fullName>
        <label>Child Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Object__c</fullName>
        <label>Criteria Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Equal To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ends With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excludes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Field__c</fullName>
        <label>Parent Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <label>Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow_Rule__c</fullName>
        <label>Workflow Rule</label>
        <referenceTo>WorkflowRule__c</referenceTo>
        <relationshipName>Workflow_Rule_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkflowRuleHelper.cls
public with sharing class WorkflowRuleHelper {
    
    	
	public static List<WorkflowRule__c> getWorkflowRuleDetails(Set<Id> ruleIds){
		return [Select Id,Name,Filter_Logic__c,Evaluation_Rule__c,
									   (Select Id,criteria_object__c,field_name__c,field_api_name__c,operator__c,field_type__c,value__c ,
									    parent_object_field__c,relationship_name__c,child_relationship_name__c
									    from Workflow_Rule_Criterias__r ),
									    (Select Id,Name,Action_Label__c,Notified_User__c,Reference_Id__c,Field_Type__c,
									     Field_Name__c,ActionType__c,Value__c,Long_Value__c,Action_Object__c,
									     Notify_user__c,Email_Template__c,User_Owner_Id__c,CrossObjectField__c,
									     Workflow_Rule__c,Additional_Emails__c,External_Field_API_Name__c,
									     externalid__c,Child_Relationship_Name__c
									     FROM Workflow_Rule_Actions__r)
									    FROM WorkflowRule__c where Active__c=true AND Id IN:ruleIds];   	
	}
	
	public static Map<Id,WorkflowRuleAction__c> getInsertRelatedRecordInfo(Set<Id> ruleIds){
        return new Map<Id,WorkflowRuleAction__c>([Select Id,(Select Name, Value__c,Reference_Id__c From Values_for_Action_Insert_Record__r ) from WorkflowRuleAction__c where Workflow_Rule__c in: ruleIds and (ActionType__c = 'Insert Related Object' )]);
    }
	
	
    
    public static Map<Id,User> getUserDetails(Set<String> userIds){
        return new Map<Id,User>([Select Name, FirstName,LastName,Id,Email from User where Id in: userIDs]);
    }
    
    
}